# Generated by Django 5.2.6 on 2025-09-05 23:07

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='About Fintaa', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_description', wagtail.fields.RichTextField()),
                ('hero_image_url', models.URLField(blank=True, help_text='URL for hero image')),
                ('story_title', models.CharField(default='Our Story', max_length=255)),
                ('story_content', wagtail.fields.RichTextField()),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_content', wagtail.fields.RichTextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('vision_content', wagtail.fields.RichTextField()),
                ('values_title', models.CharField(default='Our Values', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Get In Touch', max_length=255)),
                ('hero_description', wagtail.fields.RichTextField()),
                ('office_address', models.TextField(blank=True)),
                ('email_address', models.EmailField(default='info@Fintaa.pk', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('business_hours', models.CharField(default='24/7 Available', max_length=255)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='budget',
            field=models.CharField(blank=True, choices=[('under_5k', 'Under $5,000'), ('5k_15k', '$5,000 - $15,000'), ('15k_50k', '$15,000 - $50,000'), ('50k_plus', '$50,000+'), ('not_sure', 'Not Sure')], max_length=50),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='timeline',
            field=models.CharField(blank=True, choices=[('asap', 'ASAP'), ('1_month', 'Within 1 Month'), ('3_months', 'Within 3 Months'), ('6_months', 'Within 6 Months'), ('flexible', 'Flexible')], max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, help_text='Material icon name', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='portfolio.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='portfolio.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='URL for team member photo')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='portfolio.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
